*** Variables ***
${URL_CADASTRO}           https://automacao.qacoders-academy.com.br/user
${TEXT_NAME_CADASTRO}     //div[@class='css-wgzttu'][contains(.,'Nome')]
${TEXT_EMAIL}             //div[@class='css-wgzttu'][contains(.,'Email')]
${LISTA_USUARIOS}         css:li[class="css-iatckd"]
${PAGE}                   //ul[@class='css-76nm1l'][contains(.,'1-30 de 1841')]
${PAGE2}                  //ul[contains(.,'1-30 de 532')]